
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Gemfile
    - Rakefile
    - rwc_seed.gemspec

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets
