schoolList = [
{"name":"Eastside Elementary","address":"1776 Independence Dr","city":"Rockville","state":"SC","country":"USA"},
{"name":"Wells Middle School","address":"1812 New England Ln","city":"Rockville","state":"SC","country":"USA"},
{"name":"Dunn High School","address":"1914 French Cir","city":"Rockville","state":"SC","country":"USA"}
]
studentList = [
{"name":"Abel Cox","email":"acox@rcsd.sc.us.edu","username":"acox","password":"password","confirmed":"true","type":"student"},
{"name":"Amaya Robertson","email":"arobertson@rcsd.sc.us.edu","username":"arobertson","password":"password","confirmed":"true","type":"student"},
{"name":"Ayla Smith","email":"asmith@rcsd.sc.us.edu","username":"asmith","password":"password","confirmed":"true","type":"student"},
{"name":"Carter Clarke","email":"cclarke@rcsd.sc.us.edu","username":"cclarke","password":"password","confirmed":"true","type":"student"},
{"name":"Damien Bailey","email":"dbailey@rcsd.sc.us.edu","username":"dbailey","password":"password","confirmed":"true","type":"student"},
{"name":"Emerson George","email":"egeorge@rcsd.sc.us.edu","username":"egeorge","password":"password","confirmed":"true","type":"student"},
{"name":"Grayson Nelson","email":"gnelson@rcsd.sc.us.edu","username":"gnelson","password":"password","confirmed":"true","type":"student"},
{"name":"Jake Mason","email":"jmason@rcsd.sc.us.edu","username":"jmason","password":"password","confirmed":"true","type":"student"},
{"name":"Jose Powell","email":"jpowell@rcsd.sc.us.edu","username":"jpowell","password":"password","confirmed":"true","type":"student"},
{"name":"Kate Webster","email":"kwebster@rcsd.sc.us.edu","username":"kwebster","password":"password","confirmed":"true","type":"student"},
{"name":"Abraham Mason","email":"amason@rcsd.sc.us.edu","username":"amason","password":"password","confirmed":"true","type":"student"},
{"name":"Amelia Smith","email":"asmith2@rcsd.sc.us.edu","username":"asmith2","password":"password","confirmed":"true","type":"student"},
{"name":"Baily Moore","email":"bmoore@rcsd.sc.us.edu","username":"bmoore","password":"password","confirmed":"true","type":"student"},
{"name":"Cash Hill","email":"chill@rcsd.sc.us.edu","username":"chill","password":"password","confirmed":"true","type":"student"},
{"name":"Dante Clark","email":"dclark@rcsd.sc.us.edu","username":"dclark","password":"password","confirmed":"true","type":"student"},
{"name":"Emilia Morgan","email":"emorgan@rcsd.sc.us.edu","username":"emorgan","password":"password","confirmed":"true","type":"student"},
{"name":"Greyson Rodgers","email":"grodgers@rcsd.sc.us.edu","username":"grodgers","password":"password","confirmed":"true","type":"student"},
{"name":"Jameson Jackson","email":"jjackson@rcsd.sc.us.edu","username":"jjackson","password":"password","confirmed":"true","type":"student"},
{"name":"Josh Hill","email":"jhill@rcsd.sc.us.edu","username":"jhill","password":"password","confirmed":"true","type":"student"},
{"name":"Kate Green","email":"kgreen@rcsd.sc.us.edu","username":"kgreen","password":"password","confirmed":"true","type":"student"},
{"name":"Ace Wright","email":"awright@rcsd.sc.us.edu","username":"awright","password":"password","confirmed":"true","type":"student"},
{"name":"Amir Smith","email":"asmith3@rcsd.sc.us.edu","username":"asmith3","password":"password","confirmed":"true","type":"student"},
{"name":"Baylee Armstrong","email":"barmstrong@rcsd.sc.us.edu","username":"barmstrong","password":"password","confirmed":"true","type":"student"},
{"name":"Catlina Spencer","email":"cspencer@rcsd.sc.us.edu","username":"cspencer","password":"password","confirmed":"true","type":"student"},
{"name":"Dawson City","email":"dcity@rcsd.sc.us.edu","username":"dcity","password":"password","confirmed":"true","type":"student"},
{"name":"Emily Black","email":"eblack@rcsd.sc.us.edu","username":"eblack","password":"password","confirmed":"true","type":"student"},
{"name":"Gunnar Gardner","email":"ggardner@rcsd.sc.us.edu","username":"ggardner","password":"password","confirmed":"true","type":"student"},
{"name":"Jane Dunn","email":"jdunn@rcsd.sc.us.edu","username":"jdunn","password":"password","confirmed":"true","type":"student"},
{"name":"Juan Reid","email":"jreid@rcsd.sc.us.edu","username":"jreid","password":"password","confirmed":"true","type":"student"},
{"name":"Kaylee Red","email":"kred@rcsd.sc.us.edu","username":"kred","password":"password","confirmed":"true","type":"student"},
{"name":"Adaline Wells","email":"awells@rcsd.sc.us.edu","username":"awells","password":"password","confirmed":"true","type":"student"},
{"name":"Amy Green","email":"agreen@rcsd.sc.us.edu","username":"agreen","password":"password","confirmed":"true","type":"student"},
{"name":"Beckett Allen","email":"ballen@rcsd.sc.us.edu","username":"ballen","password":"password","confirmed":"true","type":"student"},
{"name":"Cecilia Lewis","email":"clewis@rcsd.sc.us.edu","username":"clewis","password":"password","confirmed":"true","type":"student"},
{"name":"Derek Smith","email":"dsmith@rcsd.sc.us.edu","username":"dsmith","password":"password","confirmed":"true","type":"student"},
{"name":"Enzo Jackson","email":"ejackson@rcsd.sc.us.edu","username":"ejackson","password":"password","confirmed":"true","type":"student"},
{"name":"Hannah Ross","email":"hross@rcsd.sc.us.edu","username":"hross","password":"password","confirmed":"true","type":"student"},
{"name":"Jase Stone","email":"jstone@rcsd.sc.us.edu","username":"jstone","password":"password","confirmed":"true","type":"student"},
{"name":"Juliet Jenkins","email":"jjenkins@rcsd.sc.us.edu","username":"jjenkins","password":"password","confirmed":"true","type":"student"},
{"name":"Keira Gordon","email":"kgordon@rcsd.sc.us.edu","username":"kgordon","password":"password","confirmed":"true","type":"student"}
]
facultyList = [
{"name":"Rob Campbell","email":"rcampbell@@rcsd.sc.us.edu","username":"rcampbell","password":"password","confirmed":"true","type":"faculty"},
{"name":"Steve Addy","email":"saddy@rcsd.sc.us.edu","username":"saddy","password":"password","confirmed":"true","type":"faculty"},
{"name":"April Wallace","email":"awallace@rcsd.sc.us.edu","username":"awallace","password":"password","confirmed":"true","type":"faculty"},
{"name":"Kimrey Smith","email":"ksmith@rcsd.sc.us.edu","username":"ksmith","password":"password","confirmed":"true","type":"faculty"},
{"name":"Sandy Croft","email":"scroft@rcsd.sc.us.edu","username":"scroft","password":"password","confirmed":"true","type":"faculty"},
{"name":"Karen Craft","email":"kcraft@rcsd.sc.us.edu","username":"kcraft","password":"password","confirmed":"true","type":"faculty"},
{"name":"Alice Long","email":"along@rcsd.sc.us.edu","username":"along","password":"password","confirmed":"true","type":"faculty"},
{"name":"Bethany Smith","email":"bsmith@rcsd.sc.us.edu","username":"bsmith","password":"password","confirmed":"true","type":"faculty"},
{"name":"Cherry Davis","email":"cdavis@rcsd.sc.us.edu","username":"cdavis","password":"password","confirmed":"true","type":"faculty"},
{"name":"Dale Terry","email":"dterry@rcsd.sc.us.edu","username":"dterry","password":"password","confirmed":"true","type":"faculty"},
{"name":"Eveline Johnson","email":"ejohnson@rcsd.sc.us.edu","username":"ejohnson","password":"password","confirmed":"true","type":"faculty"},
{"name":"Frank Williams","email":"fwilliams@rcsd.sc.us.edu","username":"fwilliams","password":"password","confirmed":"true","type":"faculty"},
{"name":"Grace Jones","email":"gjones@rcsd.sc.us.edu","username":"gjones","password":"password","confirmed":"true","type":"faculty"},
{"name":"Tonya Taylor","email":"ttaylor@rcsd.sc.us.edu","username":"ttaylor","password":"password","confirmed":"true","type":"faculty"},
{"name":"Caleb Ray","email":"cray@rcsd.sc.us.edu","username":"cray","password":"password","confirmed":"true","type":"faculty"}
]
schoolUserList = [
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"43"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"44"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"45"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"46"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"47"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"48"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"49"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"50"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"51"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"52"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"53"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"54"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"55"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"1"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"2"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"3"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"4"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"5"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"6"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"7"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"8"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"9"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"10"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"11"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"12"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"13"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"14"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"15"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"16"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"17"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"18"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"19"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"20"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"21"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"3"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"23"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"24"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"25"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"26"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"27"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"28"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"29"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"30"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"31"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"32"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"33"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"34"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"35"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"36"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"37"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"38"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"39"},
{"school_id":"1","start_date":"08/01/18","end_date":"12/31/50","user_id":"40"}
]
classList = [
{"name":"2nd Grade","teacher_id":"48"},
{"name":"3rd Grade","teacher_id":"50"},
{"name":"4th Grade","teacher_id":"52"},
{"name":"5th Grade","teacher_id":"54"}
]
